---
- hosts: all
  tasks:
    # - name: Delete Gitlab Project
    #   gitlab_project:
    #     server_url: http://localhost:8080
    #     validate_certs: False
    #     login_token: WnUzDsxjy8230-Dy_k
    #     name: my_first_project
    #     state: absent
    #   delegate_to: localhost

    - name: Create Gitlab Project in group Ansible
      gitlab_project:
        server_url: http://65.1.242.75:8000
        validate_certs: True
        login_user: root
        login_password: qwerty123
        name: my_first_project
        group: ansible
        path: http://65.1.242.75:8000/ansible/gitlab
        issues_enabled: False
        wiki_enabled: True
        snippets_enabled: True
        import_url: http://65.1.242.75:8000/root/my_project.git
        state: present
      delegate_to: localhost

    - name: Add a user to a GitLab Project
      community.general.gitlab_project_members:
        api_url: 'http://localhost:8080'
        api_token: 'wj6oi9dSkFfq56BnkxXw'
        validate_certs: False
        project: repo1
        gitlab_user: prahas
        access_level: developer
        state: present

    # - name: Remove a user from a GitLab project
    #   community.general.gitlab_project_members:
    #     api_url: 'https://gitlab.example.com'
    #     api_token: 'Your-Private-Token'
    #     validate_certs: False
    #     project: projectname
    #     gitlab_user: username
    #     state: absent